### ISSUE TITLE
Allow to set ground opacity

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-vuetoc#11]
There is a property to set the ground opacity in map.apps/esri API. It would be cool, if this property could be changed within the vuetoc.

Sample: https://demos.conterra.de/mapapps/resources/apps/geologie/index.html

"map": {
   "ground": {
      "opacity": 0.8
   },
...

**Comment by matthiasstein** [comment]
Added in https://github.com/conterra/mapapps-vuetoc/releases/tag/2.2.0
