### ISSUE TITLE
Integrate legend in toc (optional)

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-vuetoc#2]
As a user I want to see the legend for each layer directly in the toc. This is helpful to know which layer corresponds to the map content I see. This feature should be optional by configuration.

A similar implementation on 3.x can be seen here: https://developernetwork.conterra.de/en/downloads/bundles/forst-toc-bundle

**Comment by matthiasstein** [comment]
This feature will be included in the next release.

**Comment by matthiasstein** [comment]
Added in https://github.com/conterra/mapapps-vuetoc/releases/tag/1.1.0
